services:
  - type: web
    name: tensorflow-flask-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python3.10
